create table public."OrganizationProjects"
(
    "Id" integer generated by default as identity
        constraint "PK_OrganizationProjects"
            primary key,
    "Name"             varchar(200) not null,
    "Description"      varchar(200) not null,
    "AuthorizationKey" text         not null,
    "OrganizationId"   integer      not null
        constraint "FK_OrganizationProjects_Organizations_OrganizationId"
            references public."Organizations"
            on delete cascade,
    "ProjectStatusId"  integer                                not null
        constraint "FK_OrganizationProjects_ProjectStatuses_ProjectStatusId"
            references public."ProjectStatuses"
            on delete cascade,
    "CreatedDate"      timestamp with time zone default now() not null,
    "IsActive"         boolean                  default true  not null
);
